//
// Copyright (c) 2025 Vinnie Falco (vinnie.falco@gmail.com)
// Copyright (c) 2026 Michael Vandeberg 
// Copyright (c) 2026 Andrzej Krzemieński (akrzemi1@gmail.com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
// Official repository: https://github.com/cppalliance/capy
//
= Composite Buffers
:page-mode: explanation

In real protocols, a message to be transmitted is often composed of a couple of chunks prepared separately
in separate contiguous regions of storage. For instance, you may separately get message headers, the payload, 
and the message checksum. Trying to get them into a single contiguous region would require the user to do
unnecessary copying.

In order to address this use case, all read and write operations in Capy allow you to provide ranges 
of contiguous buffers:

[source,cpp]
----
include::example$snippets/5b_composite_buffers.cpp[tag=range_of_units,indent=0]
----


== Buffer Sequences

In order to address both the simple case of a single contiguous buffer, 
and the complex cases when the data is produced in a number of contiguous buffers, Capy introduces a concept
of a _buffer sequence_:

 * A contiguous buffer is a buffer sequence.
 * Any bidirectional range over contiguous buffers is a buffer sequence.

This generalizes the notion of a _handle_:

// Figures are sized in rem so they track the reader's font size. The UI
// bundle offers no hook for page CSS, so the rule ships with the page.
++++
<style>
.doc .imageblock.scaled > .content > img {
  width: 30rem;
  max-width: 100%;
  height: auto;
}
</style>
++++

[.scaled]
image::composite_buffer.svg[]

In the composite case, the entire range mechanism becomes a handle; but since the elements are 
cpp:const_buffer[] or cpp:mutable_buffer[], 
the contiguous regions of memory they point to are not part of the handle. 
This still allows the algorithms to copy the handle
while retaining the storage at its original location. 

Treating a single contiguous buffer as a one-element sequence is intentional, to make the library API smaller. 
Internally, it is treated as a single-element range.

While a structure looks two-dimensional, the bytes across all contiguous buffers 
are interpreted and transmitted as a single sequence: first the bytes from the first contiguous buffer,
then the bytes from the second contiguous buffer, and so on.  

The mechanism for handling ranges of buffers assumes that the number of elements will be around four.
In fact, some implementations will perform suboptimally when you use ranges of more than 16 contiguous buffers.

Serializing more buffers in one transmission would not be efficient, and you might as well merge the contents
into a single buffer.


=== The Concepts

Concept cpp:MutableBufferSequence[] tests if the type models a mutable buffer sequence,
suitable for read algorithms. It can be one of:

 * cpp:mutable_buffer[],
 * a bidirectional range of cpp:mutable_buffer[].

[source,cpp]
----
include::example$snippets/5b_composite_buffers.cpp[tag=test_mutable_buffer,indent=0]
----
 
Concept cpp:ConstBufferSequence[] tests if the type models a const buffer sequence,
suitable for write algorithms. It can be one of:

 * cpp:const_buffer[],
 * cpp:mutable_buffer[] (with the caveat that its data has determinate values),
 * a bidirectional range of either cpp:const_buffer[] or cpp:mutable_buffer[].

[source,cpp]
----
include::example$snippets/5b_composite_buffers.cpp[tag=test_const_buffer,indent=0]
----

These concepts are present in header `<boost/capy/buffers.hpp>`. 


=== Navigating Buffer Sequences

Header `<boost/capy/buffers.hpp>` also provides a couple of function objects for navigating buffer sequences.

In order to iterate over contiguous buffers themselves (as opposed to bytes),
use cpp:begin[capy::begin] and cpp:end[capy::end]:

[source,cpp]
----
include::example$snippets/5b_composite_buffers.cpp[tag=iterate,indent=0]
----

These functions treat single contiguous buffers as a one-element range of contiguous buffers:


[source,cpp]
----
include::example$snippets/5b_composite_buffers.cpp[tag=begin_end_uniform,indent=0]
----

Function cpp:buffer_length[] says how many contiguous buffers are present in the buffer
sequence. It is equivalent to

[source,cpp]
----
include::example$snippets/5b_composite_buffers.cpp[tag=length_equivalent,indent=0]
----
